### ISSUE TITLE
Better handling of telescope_id and telescope locations

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/blimpy#112]
At the moment we've hardcoded the mapping between the `telescope_id` in the sigproc header, and the telescope name / coords. [Presto also does this](https://github.com/scottransom/presto/blob/85c0cb50546b2e69b69245753e39d7ae646136a5/src/sigproc_fb.c#L70).

I suggest we add a file `ephemeris/observatories.py` (or CSV) and add a dictionary of observatories, with the mapping coded in a saner way.

**Comment by dan-rds** [comment]
Sounds easy enough, where are the telescope locations recorded? I assume you mean lat/long coords and I can't find those in presto unless it's somewhere deep in the fortran

**Comment by siemion** [comment]
If you grep the sigproc and presto source for `GB` or `AO` you will find some of the entries.  There are a few different ways these are used, including by tempo or pint for barycentering.  For sigproc they are in src/aliases.c, in tempo they are found in the file `obsys.dat` and presto has them in src/sigproc_fb.c.  Note you will also find the telescope ids and names used in various other places as well, sometimes using hardcoded definitions in some other source file.  You also often find differences in these definitions depending on which lineage your particular version of sigproc/presto descends from.

One idea would be to have some kind of a database that could be centrally updated, and then have an `update_defs` script for each of the tools.

**Comment by dan-rds** [comment]
[obsys.dat](https://github.com/UCBerkeleySETI/bl_tempo/blob/master/obsys.dat) seems right but what are those units and what are the other columns?
To be clear the `Observatory` class should have the following fields: telescope_id, short_id, telescope_name, dish_diam (if applicable), lat, lon. Anything else?

**Comment by telegraphic** [comment]
Those are _probably_ Geocentric XYZ coordinates in metres (cartesian coordinates with from Earth's centre at the origin). There's a standard coordinate conversion to convert XYZ coordinates into (latitude, longitude, elevation).

It is probably better practice to store (X, Y, Z), because (lat, lon, elev) depends on the WGS84 'prolate spheroid' model of the Earth, which is updated every now and again.

So I would have columns and a header something like:
```
#### observatories.csv ### 
# Geodetic locations of Earth-based observatories 
# 
### Table fields ###
# TELESCOPE: Name of telescope
# SIGPROC_ID: Identifier as assigned by sigproc standard
# ...
# TELESCOPE SIGPROC_ID  SHORT_SIGPROC_ID   X    Y    Z   DISH_DIAMETER REFERENCE DATE_ADDED ADDED_BY
#                                         (m)  (m)  (m)      (m)
```  

Where REFERENCE points to a url or a publication so we know where the hell the numbers come from. If we're doing it 'properly', I think a text header that is human readable that fully describes the data is important.

PS: [Astropy class that might be useful](http://docs.astropy.org/en/stable/api/astropy.coordinates.EarthLocation.html#astropy.coordinates.EarthLocation)

**Comment by dan-rds** [comment]
I opened up a pr #114 with a class and csv file. The csv file is missing:
In presto but not sigproc (missing x,y,z)

- 21,"FAST",350.0
- 64,"MeerKAT",-1
- 65,"KAT-7",-1
- 2,"Ooty",-1

The following are telescopes from sigproc that aren't in presto so I don't know what to include.

- QUABBIN
- Tasmania
- PRINCETON
- VLA2
- GB-G1
- GB-G3
- GB-G8
- NORTHERN
- MOST
- WSRT
- LWA1

**Comment by siemion** [comment]
Good sleuthing - I think we want to be able to include all of these facilities in a consistent way, and have a ready way to include others.  As an aside, this is useful (read: critical) for multi-site SETI observations as well.
