### ISSUE TITLE
fil2h5 bug -- HTR data

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/blimpy#116]
**Describe the bug**
Chunk dimensions not calculated correctly for `fil2h5` on high time res data

**To Reproduce**
```bash
(base) dancpr@blc00:/datax2/users/dancpr/test_rq/collate/blc00$ fil2h5 guppi_58948_45245_6051771717_J1019-5749_S_0001.0001.stokesI.fil
bshuf filter already loaded, skip it.
blimpy.io.file_wrapper WARNING  Selection size of 2.86 GB, exceeding our size limit 1.00 GB. Instance created, header loaded, but data not loaded, please try another (t,v) selection.
blimpy.waterfall INFO     Detecting high time resolution data.
Traceback (most recent call last):
  File "/opt/conda/bin/fil2h5", line 8, in <module>
    sys.exit(cmd_tool())
  File "/opt/conda/lib/python3.7/site-packages/blimpy/fil2h5.py", line 87, in cmd_tool
    make_h5_file(filename, out_dir = opts.out_dir, new_filename = opts.new_filename, max_load = opts.max_load)
  File "/opt/conda/lib/python3.7/site-packages/blimpy/fil2h5.py", line 54, in make_h5_file
    fil_file.write_to_hdf5(new_filename)
  File "/opt/conda/lib/python3.7/site-packages/blimpy/waterfall.py", line 306, in write_to_hdf5
    write_to_hdf5(self, filename_out, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/blimpy/io/hdf_writer.py", line 23, in write_to_hdf5
    __write_to_hdf5_heavy(wf, filename_out, f_scrunch=f_scrunch, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/blimpy/io/hdf_writer.py", line 67, in __write_to_hdf5_heavy
    dtype=wf.data.dtype)
  File "/opt/conda/lib/python3.7/site-packages/h5py/_hl/group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 104, in make_new_dset
    raise ValueError(errmsg)
ValueError: Chunk shape must not be greater than data shape in any dimension. (2048, 1, 512) is not compatible with (3000000, 1, 256)
```

**Expected behavior**
Not crash

**Comment by texadactyl** [comment]
Downloading that file (if I could find it) would take forever and a day.  So, I was able to reproduce the same symptoms with a Filterbank file that I generated with a tool https://github.com/texadactyl/fbgen 

I'll see if I can make some progress on finding out what's going wrong in fil2h5.

**Comment by texadactyl** [comment]
The subject FIL has 3,000,000 samples with 256 frequencies ("high time resolution data").  I generated a similar huge FIL ("high frequency resolution data") and experienced a similar exception.

The subject FIL and the one I generated required hdf5_writer/__write_to_hdf5_heavy() processing.
A call is made to Waterfall/_get_chunk_dimensions().
Since abs(tsamp) < 1e-3, a chunk_dim of (2048,1,512) is returned to caller.
Eventually, h5py/dataset.py raises the expected incompatibility exception.

It seems to me that _get_chunk_dimensions() needs a re-think to stop hard-coding the dimension specifications returned based on foff and tsamp.  I do not know what the requirements are.

Anyways, I cheated by changing the hard-coded high frequency return to be (1,1,256) just to see what would happen.  Yes, it ran to completion and made a perfectly usable huge h5.

**Comment by texadactyl** [comment]
@telegraphic 
I believe that I fixed it properly.
Feedback?

**Comment by texadactyl** [comment]
No, I did not.

**Comment by texadactyl** [comment]
I have not fixed it properly.  But, I think that I've come up with a second temporary solution which is better than the first one although it is not optimal for the general (multiple) cases.  The fil2h5 utility should not crash for high time resolution data, high frequency resolution data, the medium case, or the none of the above case.  The _get_chunk_dimensions() function returns a guess to __write_to_hdf5_heavy().  Then, each of the 3 dimension is compared to its wf.selection_shape counterpart:

```
    if chunk-computed dimension > selection shape counterpart:
        Replace this chunk-computed dimension with its selection shape counterpart
    else:
        Use the chunk-computed dimension as-is
```

Not beautiful but it will stop crashes and provide a reasonable solution until the general case can be figured out.

Issues that I see in solving the general case:

(1) I am not clear on what the actual requirements are for blimpy writing to HDF5 files from Filterbank files.  Chalk that up to a lack of history with your organization.  In my career with computer manufacturers and in the financial industry, requirements are developed/provided as a starting point.  I realize that scientists are busy doing science and often have a different modus operandi when it comes to software development.  Don't take that the wrong way.

(2) The _get_chunk_dimensions() function is being called for both creating Filterbank files (presumably from guppi) and for creating HDF5 files.  I doubt if its current code really satisfy both needs.  It looks like its calculations are for writing Filterbank files.

(3) Automatic calculations like in _get_chunk_dimensions() will always be guesses, even when educated.  It's always possible that someone will want to use the file in a way that is counter to what the automation guessed when creating the file.  For eaxample, I can imagine some application reading down the time cadence for a file that was guessed to be high frequency resolution.   One solution to that is make both access paths available in an efficient manner through indexing.  See https://www.slideshare.net/HDFEOS/jxp-50716706 .  Yes, this would cause a lot of blimpy rewrite.

**Comment by texadactyl** [comment]
Currently .....

```fil2h5``` does the conversion.

However, ```turboSETI``` now reports this on the HDF5 file:
```
ValueError: Don't attempt to use High Time Resolution (HTR) files with turboSETI. TurboSETI is designed to search for narrowband signals -- the maximum doppler drift we can expect due to the motion of celestial bodies is a few Hz/s. The high time resolution products (ending 0001.fil) has ~0.5 MHz resolution and ~100 us integrations, so you'd be looking at insane drift rates. Issue #117.
data_handler    ERROR    data_handler.py:load_drift_indexes: time integration steps = 524288!
data_handler    ERROR    data_handler.py:load_drift_indexes: file drift_indexes/drift_indexes_array_19.txt not found!
```
