### ISSUE TITLE
DC blanking option

### ISSUE THREAD

**Issue by siemion** [UCBerkeleySETI/blimpy#124]
It might be best for the DC blanking option to be "off" by default, as it only works on a subset of filterbank data...

**Comment by telegraphic** [comment]
agreed!

**Comment by texadactyl** [comment]
@telegraphic 
This one can be closed.
Note in cmd_tool:
```
    parser.add_argument('-D', action='store_false', default=False, dest='blank_dc',
                       help='Use to blank DC bin.')

```
