### ISSUE TITLE
bldice/fil2h5 failing

### ISSUE THREAD

**Issue by mattlebofsky** [UCBerkeleySETI/blimpy#129]
**Describe the bug**
bldice command is failing (without producing expected output) while trying to dice/convert filterbank file to hdf5. (It works when dicing without doing conversion step). Likewise fil2h5 command is failing with similar errors when simply trying to convert filterbank to hdf5.

**To Reproduce**
Download test file (73 MB):
http://setiathome.berkeley.edu/~mattl/blc00_guppi_58873_39261_NGC5194_0136.rawspec.0002.fil
Run either command:
fil2h5 blc00_guppi_58873_39261_NGC5194_0136.rawspec.0002.fil
bldice -f ./blc00_guppi_58873_39261_NGC5194_0136.rawspec.0002.fil -o out.h5 -b 2100 -e 2110 -x h5

**Expected behavior**
A .h5 file is to be written (either diced or whole, depending on which program is run)

**Setup**
python3.8 - and
$ pip freeze
astropy==4.0.1.post1
blimpy==2.0.0
cycler==0.10.0
Cython==0.29.19
h5py==2.10.0
hdf5plugin==2.3.0
kiwisolver==1.2.0
matplotlib==3.2.1
numpy==1.18.4
pandas==1.0.3
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
scipy==1.4.1
six==1.15.0
turbo-seti==0.7.2

**Additional context**
I thought this may have been an issue with filterbanks having 8-integer values (instead of 32-bit floats), or they were too large (9 GB) or on an NFS mounted filesystem. As shown by the very simple, standard, reproducible cases above, these were all red herrings.

**Comment by texadactyl** [comment]
Both complete successfully for me:
```
fil2h5 blc00_guppi_58873_39261_NGC5194_0136.rawspec.0002.fil
blimpy.waterfall INFO     Conversion time: 0.43sec
```
and
```
bldice -f ./blc00_guppi_58873_39261_NGC5194_0136.rawspec.0002.fil -o out.fil -b 2100 -e 2110 -x fil
blimpy.dice     INFO     Writing to out.fil
blimpy.dice     INFO     Extacting from 2099.12109375 MHz to 2110.83984375 MHz.
blimpy.waterfall INFO     Conversion time: 0.02sec
```
Versions:
```
Xubuntu 20.04 LTS
Python 3.8.2
Cython==0.29.17
h5py==2.10.0
hdf5plugin==2.3.0
numpy==1.18.4
scipy==1.4.1 
```

**Comment by mattlebofsky** [comment]
Note: when I use the conda environment Danny set up (with 250+ installed python libraries/packages) I don't get these errors. If I use a fresh python3.8 environment and do a `pip install blimpy` and get only the ~10 dependencies blimpy requires then I get these errors. So it seems like I need some other package that `pip install blimpy` isn't picking up.

**Comment by texadactyl** [comment]
Same successful results for me in a Python3 virtual environment.  Package versions seem to be the same.  It might be something in the difference between Ubuntu 16.04 over netboot (GB) and 20.04 (my test machine).

**Comment by texadactyl** [comment]
I am going to research both of the h5-related packages that are in use.  Question to myself: what O/S resources are they dependent on?

**Comment by mattlebofsky** [comment]
I've discovered some issues with the dev environment at GB causing the hdf5 issues I was seeing, and it sounds like there is work in progress for the large file handling, so I'm going to close this issue. Thank you for all your help!
