### ISSUE TITLE
blimpy falling to plot waterfall

### ISSUE THREAD

**Issue by mirosaide** [UCBerkeleySETI/blimpy#130]
I ran the file GBT_57459_34623_HIP65352_OFF_fine.h5 on turbo, I had the outputs (.dat and .log) files.

Then I was trying to plot a waterfall using the following code:

``` from blimpy import Waterfall

fil1 = Waterfall('GBT_57459_34623_HIP65352_OFF_fine.h5')

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

fil1.plot_waterfall()

plt.show() 


I even tried to place constrains (f_start and f_stop) but still getting the following error:


blimpy.io.base_reader WARNING  Selection size of 15.77 GB, exceeding our size limit 1.00 GB. Instance created, header loaded, but data not loaded, please try another (t,v) selection.
Traceback (most recent call last):
  File "HIP65352_test.py", line 9, in <module>
    fil1.plot_waterfall()
  File "/home/mirosaide/.local/lib/python3.7/site-packages/blimpy/plotting/plot_waterfall.py", line 17, in plot_waterfall
    plot_f, plot_data = wf.grab_data(f_start, f_stop, if_id)
  File "/home/mirosaide/.local/lib/python3.7/site-packages/blimpy/waterfall.py", line 293, in grab_data
    plot_data = np.squeeze(self.data[t_start:t_stop, ...,i0:i1 + 1])
IndexError: too many indices for array

**Comment by texadactyl** [comment]
This would have been a more direct failure report:
```
Traceback (most recent call last):
  File "essai.py", line 8, in <module>
    fil1.plot_waterfall()
  File "/home/elkins/.local/lib/python3.8/site-packages/blimpy/plotting/plot_waterfall.py", line 17, in plot_waterfall
    plot_f, plot_data = wf.grab_data(f_start, f_stop, if_id)
  File "/home/elkins/.local/lib/python3.8/site-packages/blimpy/waterfall.py", line 311, in grab_data
    raise Exception("Waterfall.grab_data: Too much data requested: samples={}, freq={}"
Exception: Waterfall.grab_data: Too much data requested: samples=16, freq=264503296
```
The request was to grab 17 GB of data (16 * 264503296 * 4 bytes) for the plot.  Unfortunately, the request exceeded the RAM available.

**Comment by texadactyl** [comment]
@mirosaide 
I modified your program to use f_start = f_stop = 1200 and it still ended this way.

@telegraphic --
In grab_data, at the point of exception:
```
plot_data = np.squeeze(self.data[t_start:t_stop, ..., i1:i0 + 1])
```
t_start = 0, t_stop = 16, i0 = i1 = 238569574 when an exception is raised.
I modified this function to set up t_start and t_stop when None is supplied.
One would think that this would narrow the request down but it doesn't.
Is this another part of the HDF5 discussion?

**Comment by texadactyl** [comment]
The Waterfall.info() for this HDF5 file:
```
--- File Info ---
DIMENSION_LABELS : [b'frequency' b'feed_id' b'time']
        az_start :                              0.0
       data_type :                                1
            fch1 :                1876.46484375 MHz
            foff :       -2.835503418452676e-06 MHz
      machine_id :                               20
           nbits :                               32
          nchans :                        264503296
            nifs :                                1
     source_name :                     HIP65352_OFF
         src_dej :                      4:43:26.996
         src_raj :                       13:23:39.1
    telescope_id :                                6
           tsamp :                     17.986224128
   tstart (ISOT) :          2016-03-12T09:37:03.000
    tstart (MJD) :               57459.400729166664
        za_start :                              0.0

Num ints in file :                               16
      File shape :               (16, 1, 264503296)
--- Selection Info ---
Data selection shape :               (16, 1, 264503296)
Minimum freq (MHz) :               1126.4648465855034
Maximum freq (MHz) :                    1876.46484375
```

**Comment by irfnt** [comment]
hello i am reading .fil file using blimpy but i am getting error , ZeroDivisionError: division by zero . 
from blimpy import Waterfall
import pylab as plt
import numpy as np
import math
from scipy import stats, interpolate
file_path='GBT_Lband_PSR.fil'
obs = Waterfall(file_path)

**Comment by texadactyl** [comment]
@irfnt Where (URL) is GBT_Lband_PSR.fil ?

**Comment by irfnt** [comment]
http://www.cv.nrao.edu/~sransom/GBT_Lband_PSR.fil

**Comment by texadactyl** [comment]
@irfnt - Thank you for the URL.  I took it out for a spin.

Here is the header:

{'telescope_id': 6, 'rawdatafile': 'GBT_Lband_PSR.fil', 'source_name': 'Mystery_PSR', 'data_type': 1, 'foff': -1.0, 'nchans': 96, 'tsamp': 7.2e-05, 'nbeams': 1, 'nbits': 4, 'src_raj': <Angle 16.72725 hourangle>, 'src_dej': <Angle -12.41630556 deg>, 'tstart': 53010.48482638889, 'az_start': 0.0, 'fch1': 1447.5, 'za_start': 0.0, 'machine_id': 4, 'nifs': 1, 'nsamples': 531000}

@telegraphic  
As you can see, nbits = 4 which leads to an invalid nbytes value (0) in calc_n_ints_in_file():
```
def calc_n_ints_in_file(filename):
    """ Calculate number of integrations in a given file """
    # Load binary data
    h = read_header(filename)
    n_bytes  = int(h['nbits'] / 8) # <<< invalid for nbits = 2 or 4

    n_chans = h['nchans']
    n_ifs   = h['nifs']
    idx_data = len_header(filename)
    f = open(filename, 'rb')
    f.seek(idx_data)
    filesize = os.path.getsize(filename)
    n_bytes_data = filesize - idx_data

    if h['nbits'] == 2:
        n_ints = int(4 * n_bytes_data / (n_chans * n_ifs))
    else:
        n_ints = int(n_bytes_data / (n_bytes * n_chans * n_ifs))

    # Give the FD back to the O/S.
    f.close()

    return n_ints
```

That if statement in the middle needs a change as follows:
```
    if h['nbits'] == 2:
        n_ints = int(4 * n_bytes_data / (n_chans * n_ifs))
    elif h['nbits'] == 4:
        n_ints = int(2 * n_bytes_data / (n_chans * n_ifs))
    else: # 8, 16, or 32-bit fields
        n_bytes  = int(h['nbits'] / 8)
        n_ints = int(n_bytes_data / (n_bytes * n_chans * n_ifs))
```
Once I get past this, there may be some other issues with 2- and 4-bit integers.

**Comment by texadactyl** [comment]
Also, I see no reason for the open, seek, and close file.  Part of some ancient code?

**Comment by irfnt** [comment]
@texadactyl  thank you for your help,  blimpy is a universal file reader, can we read .fits file using blimpy.

**Comment by texadactyl** [comment]
@telegraphic 

(1) If you don't get to the header['nbits'] issues, I'll try to look tomorrow.
Files looking at header.n_ints_in_file:
./hdf_reader.py
./base_reader.py
./fil_reader.py
./hdf_writer.py

(2) Another issue: in fil_reader.py __init__(), I saw this:
```
self._n_bytes = int(self.header['nbits'] / 8)  #number of bytes per digit.
```
which is used in read_data() and read_blob() of fil_reader.py only.

**Comment by texadactyl** [comment]
@irfnt 
For a FITS file interface, I recommend using Astropy's API:
https://docs.astropy.org/en/stable/io/fits/index.html?highlight=fits

**Comment by irfnt** [comment]
@texadactyl  can you give me URL so i can download the HDF5 raw guppi files and read and read it using blimpy .

**Comment by texadactyl** [comment]
Start simple:  http://blpd0.ssl.berkeley.edu/Voyager_data/

**Comment by texadactyl** [comment]
@mirosaide 
Are you still having the same anomaly symptoms with the current github version of blimpy?
