### ISSUE TITLE
Add lazy reads and streaming for io

### ISSUE THREAD

**Issue by FX196** [UCBerkeleySETI/blimpy#132]
**Is your feature request related to a problem? Please describe.**
Currently blimpy reads in the entire file for functions like `bldice`, doing this for large files that may be larger than memory would be infeasible. This has been shown in #129 

**Describe the solution you'd like**
For features like `bldice` and `fil2h5`, only small sections of the file needs to be accessed at a time. We can use lazy reads that repeatedly overwrite a numpy array of reasonable size to stream the data.

**Comment by FX196** [comment]
Nevermind, I realize streaming is already implemented in `fil_writer` and `hdf_writer`

**Comment by texadactyl** [comment]
@FX196 
Issue #129 is probably a local environment problem.  I could not reproduce that issue independently and Matt could not either on other machines.

However, blimpy does have HDF5 handling issues.  There are several functions that attempt to populate all of the frequencies (could be hundreds of millions) and read all of the data into an array for plotting.  E.g. Waterfall grab_data().  Also, the error reporting could be more specific using the raise Exception function.

I do not have a solution for this barring a major rewrite using another methodology to either replace  HDF5 or employing an augmentation such as this: https://www.slideshare.net/HDFEOS/hdf-fast-query-shalf

**Comment by texadactyl** [comment]
It is probably too expensive to change blimpy fundamentally, at least in the near future.  SETI is a science organization, not a software development organization.  However, documentation could guide users to solutions that work well enough.

For example, GBT_57459_34623_HIP65352_OFF_fine.h5 cannot be plotted in its entirety.  See issues #130 and #134.  But, it is possible to use ```bldice``` and ```bl_scrunch``` to subset large files into a smaller file for plotting.

**Comment by FX196** [comment]
Hi @texadactyl, I think #129 is a problem with h5py. If you uninstall h5py and reinstall with `pip3 install --no-binary=h5py h5py`, everything works fine. I'll see if I can update our `setup.py` to enforce this.

And yes, we do need better implementation regarding hdf5. Perhaps lazy reads are still needed (e.g. plotting sections of the file)

**Comment by texadactyl** [comment]
I was never able to reproduce Matt's issue.  I never used the --no-binary option.  I was able to succeed in both virtual and non-virtual environments.  Puzzling.

@mirosaide is still trying to figure out how small to make his frequency interval with GBT_57459_34623_HIP65352_OFF_fine.h5 in order to get plot_waterfall() to succeed.

I was able to get plots when I created a narrow range:
```
bldice -f GBT_57459_34623_HIP65352_OFF_fine.h5 -o xx.h5 -b 1510 -e 1550
```

**Comment by mirosaide** [comment]
I trying this bash script then when I tried to plot I got this:

Traceback (most recent call last):
  File "HIP65352_test.py", line 3, in <module>
    fil1 = Waterfall('xx.h5')
  File
"/home/mirosaide/.local/lib/python3.7/site-packages/blimpy/waterfall.py",
line 97, in __init__
    load_data=load_data, max_load=max_load)
  File
"/home/mirosaide/.local/lib/python3.7/site-packages/blimpy/io/file_wrapper.py",
line 47, in open_file
    load_data=load_data, max_load=max_load)
  File
"/home/mirosaide/.local/lib/python3.7/site-packages/blimpy/io/hdf_reader.py",
line 39, in __init__
    self.read_header()
  File
"/home/mirosaide/.local/lib/python3.7/site-packages/blimpy/io/hdf_reader.py",
line 113, in read_header
    self.header[key] = val.decode('ascii')
AttributeError: 'str' object has no attribute 'decode'



*Ramiro Caisse Saide*
*MPhil/PhD Research Student*
Department of Physics
University of Mauritius
Contact Number: +258 845672884




Richard Elkins <notifications@github.com> escreveu no dia sábado,
30/05/2020 à(s) 19:40:
