### ISSUE TITLE
change to populate_freqs

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/blimpy#137]
From #blimpy_etc slack (Dominic LeDuc):

> [dld] Is there a way to get the array of frequencies for a Waterfall object  without having to do obs.container.populate_freqs()  where obs is a Waterfall object?  I’ve noticed obs.freqs doesn’t get set until some function calls populate_freqs() or I manually call it. Is there some other way
to get obs.freqs without doing this?

> [dancpr] Waterfall used to do this, but generating the frequency array takes a relatively long amount of time, so is now only generated as required.
I think we should tidy this, and bring populate_freqs access up a level so you don't need to do the container.populate_freqs() . I just did a quick timing and it's quicker to call np.arange(f_start, f_stop, f_chanbw) than to do np.arange(N_chans) * f_chanbw + f_start) , so we can speed up also

**Comment by texadactyl** [comment]
```
get_freqs = lambda arg_wf: np.arange(0, arg_wf.header['nchans'], 1, dtype=float) * arg_wf.header['foff'] + arg_wf.header['fch1']
```

As a stand-alone function:
```
wf = Waterfall(FILTERBANK_FILE)
freqs = wf.container.populate_freqs()
sum1 = np.sum(freqs)
freqs = get_freqs(wf) # Could be inserted into waterfall.py as a member function
sum2 = np.sum(freqs)
assert sum1 == sum2
```

Added to the Waterfall class as a member function:
```
wf = Waterfall(FILTERBANK_FILE)
freqs = wf.get_freqs()
```

**Comment by texadactyl** [comment]
@telegraphic 
This one can be closed.

**Comment by texadactyl** [comment]
But, it needs documentation.
