### ISSUE TITLE
Not all files are closed explicitly or implicitly

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/blimpy#138]
**Describe the bug**
In both io/fil_reader.py/read_data() and io/sigproc.py/calc_n_ints_in_file(), a file is opened, read, but never closed.  If these functions were called in a loop in the same process, it is possible to run out of Linux/Unix file descriptors.  

Will submit a pull request.

**To Reproduce**
Just view the source code.  One can see that the file descriptors are never closed explicitly or implicitly.

**Expected behavior**
File closure explicitly or implicitly.

**Screenshots**
N/A

**Setup**
 - Python version: 3.8.3
 - Blimpy version: current github

**Additional context**
Found by Sean O'Brien and Dominic Le Duc while running into an unrelated issue.

**Comment by telegraphic** [comment]
Nice catch, have just merged the pull request, so can this be closed now?
