### ISSUE TITLE
blimpy is out of date on pypi

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/blimpy#150]
**Describe the bug**
Blimpy is out of date on pypi.  The version is bumped to 2.0.1 in PR #146 setup.py.

**To Reproduce**
1. pip3 uninstall -y blimpy
2. pip3 install blimpy # from pypi
3. Run pytest in turbo_seti
4. See OS errors.

**Expected behavior**
Successful run of pytest in turbo_seti

**Setup**
 - Python 3.8
 - Blimpy version: pypi

**Comment by texadactyl** [comment]
What is needed is for @telegraphic to do one of the following:
* Update blimpy on pypi.
* Delete blimpy from pypi i.e. stop using pypi.

It is not hard to stop using pypi because the following command is equivalent to installing blimpy from pypi:
```pip install git+https://github.com/UCBerkeleySETI/blimpy```

**Comment by telegraphic** [comment]
Updated -- https://pypi.org/project/blimpy/
