### ISSUE TITLE
blimpy.guppi module - add support for .raw multiantenna

### ISSUE THREAD

**Issue by siemion** [UCBerkeleySETI/blimpy#155]
There is now a new feature in the BL guppi .raw standard that includes support for multiantenna arrays (e.g. MeerKAT) - as documented here: https://github.com/UCBerkeleySETI/bl_docs/blob/master/026_meerkat_data_format/MeerKAT_rawdata_format.pdf

Could we add support for this feature within blimpy.guppi?

**Comment by texadactyl** [comment]
Please check me: Multi-antenna (multibeam?) would have to be supported from guppi to filterbank to HDF5.  It would also have to be supported by turbo_seti.

Two challenges:
* Currently only 8-bit, 16-bit and 32-bit data elements are supported in blimpy.  Is this restriction acceptable?
* The current filterbank and HDF5 data shape is (time value, beam_number=1, frequency).  I have never seen a file in my limited experience where the beam number wasn't specified to be 1.  I don't think that multi-beam is currently viable in blimpy at the moment.

@telegraphic ?

**Comment by siemion** [comment]
Zeroth order support could be just specifying which antenna (of N antennas) would be extracted when running any of the guppi raw related functions.  Default would be to just extract antenna 0.  Then whatever was returned by that function would be compatible with any functions that relied on it, and an entire multi-antenna .raw could be read with successive calls cycling through all available antennas 0..N-1

**Comment by texadactyl** [comment]
This format looks different enough that a new blimpy MeerKAT utility ("meer2fil") should be developed to filter on telescope ID and write to a standard blimpy filterbank file in the usual (time, 1, frequency) shape.  The output side of things could leverage the existing blimpy io modules.  Then, anything that can read filterbank files can process the MeerKAT data (E.g. turbo_seti).

Make sense?

**Comment by texadactyl** [comment]
Another thought:

Instead of leveraging blimpy io for the output side, a new MeerKAT-to-Filterbank conversion utility could be written entirely in Julia. Then, the resultant Filterbank files could be read by existing programs like turbo_seti.  This would be an excellent teaching project for a new SETI staff member or an intern.

**Comment by siemion** [comment]
The goal here is to be able to extend the .raw read functionality blimpy already has to the new multi-antenna .raw specification.  This would not typically be used for wholesale conversion of files, but just to extract small pieces for voltage analysis.  This brings up the larger point of blimpy's support for voltage data, as compared with total power or even full-Stokes integrated spectrotemporal products (e.g. filterbank or hdf5).  I'm not sure who is currently using this functionality, but as we ramp our activities with interferometers it is going to become more and more useful.

**Comment by telegraphic** [comment]
Wondering whether we should collaborate with https://baseband.readthedocs.io/en/stable/ on this...

**Comment by texadactyl** [comment]
This problem has been solved in other pipelines without requiring changes to blimpy.
