### ISSUE TITLE
Make numba optional dependency / remove numba

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/blimpy#176]
Currently numba is only used in [one section of code](https://github.com/UCBerkeleySETI/blimpy/blob/da2fa380e47a4e2114440d0eb1dcb8af49a643c0/blimpy/waterfall.py#L352).

Not quite convinced that speeding this code up warrants an additional dependency, so suggest either making it optional or removing. 

Alternatively if more use of numba JIT is planned I could be convinced!

**Comment by texadactyl** [comment]
I ran into a case where numba crashed.  The data array was larger than 4 GB (is 32-bits a magic width?).  Anyways, here in blimpy, its a moot issue now.
