### ISSUE TITLE
Conflict with SIGPROC

### ISSUE THREAD

**Issue by griffinfoster** [UCBerkeleySETI/blimpy#18]
There is an annoying collision with sigproc, as sigproc has a file named filterbank.py. If you all ready have sigproc installed then the sigproc/filterbank.py will be imported, and no fun is had. I am not sure what the solution is, maybe:

1. rename the module
2. or, note in the documentation that this conflict occurs and then provide a solution

**Comment by telegraphic** [comment]
Hmm, that is unfortunate. Is this a conflict with PRESTO or sigproc or sigpyproc or something else?

Changing the name now would be particularly irritating, but unsure what a good workaround is.

**Comment by griffinfoster** [comment]
It depends on what the aim of this package is. If there will remain support for reading raw files it would make sense to change the name to something more generic. Something to do with the different interfaces for BL?

**Comment by siemion** [comment]
I agree renaming would be more consistent with how I imagine this tool will be used.

**Comment by telegraphic** [comment]
Ok, well if we are going to rename it, how about to `blio` (BL I/O)? 

PS: At Emilio's suggestion and after some acronym gymnastics, we should start calling the Hz resolution spectra 'Breakthrough Listen Ultra Fine Frequency Filterbank Files' (bluff files)
