### ISSUE TITLE
Add rawhdr command line utility and a callable function

### ISSUE THREAD

**Issue by texadactyl** [UCBerkeleySETI/blimpy#182]
```rawhdr  FILEPATH``` - command line utility to print all of the guppi header fields.

```blimpy.rawhdr.get_obsnchan(FILEPATH)``` - callable function to retrieve the number of observation (coarse) channels.

**Comment by david-macmahon** [comment]
FWIW, I put this bash function definition in my `~/.bash_aliases` file:

```
function rawhd()
{
  /usr/bin/fold ${1:?usage: rawhd RAW_DATASET [PATTERN]} | sed '/^END /q' | grep "$2" | sed 's/ *$//'
}
```
