### ISSUE TITLE
Can we use blimpy to process other telescope data file if we convert into filterbank data ?

### ISSUE THREAD

**Issue by irfnt** [UCBerkeleySETI/blimpy#185]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by irfnt** [comment]
i want to use blimpy to process filterbank data of 8bit, 4bit but giving me an error,  my question is that blimpy only process the UC data or we can use it for another datafile also like Parkes, or GBT.

**Comment by texadactyl** [comment]
As long is the header and data are well-formed, it should work.
I would stick to 32-bit floating-point power values.
Install blimpy from github as pypi is out of date.

**Comment by texadactyl** [comment]
Questioned answered?  Close?

**Comment by irfnt** [comment]
thnak you .
