### ISSUE TITLE
Are we using a new matplotlib?

### ISSUE THREAD

**Issue by jeenriquez** [UCBerkeleySETI/blimpy#22]
/opt/pyve/woodpy/lib/python2.7/site-packages/blimpy-1.1.0-py2.7.egg/blimpy/filterbank.py:709: MatplotlibDeprecationWarning: The set_axis_bgcolor function was deprecated in version 2.0. Use set_facecolor instead.
  axHeader.set_axis_bgcolor('white')

**Comment by telegraphic** [comment]
(closing issue)
