### ISSUE TITLE
Unable to plot using filterbank

### ISSUE THREAD

**Issue by nlifset1** [UCBerkeleySETI/blimpy#24]
I'm running blimpy from the command line trying to plot a filterbank file using the following command:
python /path/to/filterbank.py <filename>

I get the error "ValueError: Attempted relative import in non-package". I have had some success by going into my cloned version of blimpy and taking out dots (".") that are in front of many functions. I believe this is an issue with the latest version of blimpy.

**Comment by jeenriquez** [comment]
Thanks Noah. 
Danny, this is related to the Py3 update. I just don't want to undo your changes. Could you fix it?

**Comment by telegraphic** [comment]
Hi @nlifset1 and @jeenriquez -- this is unfortunate, buuuut I'm not changing it back.  You'll have to use blimpy as a package, and not do the sneaky method of avoiding installing it. Sorry to be inflexible here, but making it a package that can be installed with pip, and having Py3 support, take priority here IMO.

**Comment by jeenriquez** [comment]
@telegraphic , 
To some degree I disagree with this, given the people that actually is using the code now, and the complications of installing it in the BL cluster in GBT, this is inconvenient. However, what is done is done, and better to find solutions to coexist for the future. (thus the virtual environment conversation ... but outside the context here).  In any case, I'll give it a chance for now, but if I see that this is making life more difficult for the main users of this code, we'll have another talk about this.

**Comment by siemion** [comment]
Could blimpy be installed in a docker container?

**Comment by jeenriquez** [comment]
That is another possibility, but whatever the solution is, it should make life easy for everyone. I don't have experience with docker containers myself.

**Comment by siemion** [comment]
This is somewhat outside the scope of this thread, but we should not be constantly modifying the system-level python installation on the BL compute nodes.  This environment primarily exists to support data collection and pipeline analysis.  

Anyone using the cluster for later stage analysis should be doing so with a sandboxed python environment of some kind, of which there are many different varieties.  Clearly a critical feature of such an environment is the ability to install packages.

Moreover, everyone who uses python should learn to install their own packages in their own environment - this is a mission critical skill.

**Comment by jeenriquez** [comment]
I agree with that. That is why we are using virtual environments. But only works as long as everyone is also able to create their own environments. The current idea is that people could just use a generic python virtual environment which is being developed by Danny at the moment.

Maybe best to move this to a live conversation during the Monday workshop or something like that.

**Comment by telegraphic** [comment]
(Closing issue)
