### ISSUE TITLE
Waterfall from existing data array + header dict combo currently broken (`setup_freqs()` missing)

### ISSUE THREAD

**Issue by Sofysicist** [UCBerkeleySETI/blimpy#264]
I was trying to use the header_dict + data_array method for creating a Waterfall object, and it looks like it refers to a function that is no longer in the waterfall.py file (`_self.setup_freqs()`). This functionality would be useful (for me, and hopefully others!) if it was brought back, because I'd like to identify RFI-heavy channels with AOFLAGGER, modify the blimpy data array, and visualize the modified array with blimpy plotting tools.

https://github.com/UCBerkeleySETI/blimpy/blob/18a81317920d4ffb239760b06301ff632ae38044/blimpy/waterfall.py#L116

Any help tracking down that original function would be appreciated - I can't seem to find it anywhere else in the repo at a glance

**Comment by texadactyl** [comment]
I went all the way back to version 1.3.4 i.e. https://github.com/UCBerkeleySETI/blimpy/tree/1.3.4
The last commit for this version was on Nov 29, 2018.

There is no ```_setup_freqs``` function in waterfall.py.

**Comment by texadactyl** [comment]
Anyone reading this issue should not be distracted by the ```_setup_freqs``` function that is defined in the Reader object of the blimpy/io/base_reader.py source file.  Unfortunately, blimpy has some function names that are repeated at multiple levels.

**Comment by texadactyl** [comment]
@Sofysicist 
My question about this issue still needs resolution.  I want to make sure that (a) I interpreted your request correctly and (b) this proposed capability is still of interest.

**Comment by Sofysicist** [comment]
Agree with your definition of the desired function here, thanks. I actually just ran into a need for this functionality again (making a waterfall object from an existing data array and header dictionary), so it is definitely still-of-interest!

**Comment by texadactyl** [comment]
@Sofysicist 

I am thinking about a simple interface to produce a blimpy Waterfall object.  Inspiration comes from https://github.com/UCBerkeleySETI/turboseti_stream/blob/main/turboseti_stream/doppler_finder.py, the Gnu Radio project of Summer 2021.

```
from blimpy import Waterfall

class Waterstream():

    def __init__(self, 
                 data_matrix,
                 source_name,
                 src_raj,
                 src_dej,
                 tstart,
                 tsamp,
                 f_start,
                 f_stop,
                 n_fine_chans,
                 n_ints_in_file)
        """
        Parameters
        ----------
        data_matrix : Numpy array of float32
            shape: (n_ints_in_file, 1, n_fine_chans)
        source_name : str
            E.g. "Voyager-1"
        src_raj : float
            Right Ascension (J2000) of source (hours, hhmmss.s)
        src_dej : float
            Declination (J2000) of source (degrees, ddmmss.s)
        tstart : float
            Observation start time in MJD.  
        tsamp : float
            Time interval in seconds between integrations.  
        f_start : float
            First fine frequency for the data matrix, corresponds to column 0.
        f_stop : float
            Last fine frequency for the data matrix, corresponds to column -1.
        n_fine_chans : int
            Number of fine channels in the data matrix (column count).  
        n_ints_in_file : int
            Number of time integrations in the data matrix (row count).  
        """
```
So, Waterfall construction is like this:
```
waterfall = Waterstream(data_matrix,
                         source_name,
                         src_raj,
                         src_dej,
                         tstart,
                         tsamp,
                         f_start,
                         f_stop,
                         n_fine_chans,
                         n_ints_in_file)
```
The newly-instantiated waterfall object inherits the Waterfall properties and member functions (info, write_to_hdf5, plot routines).  One would have to be careful not to access the file-oriented properties (E.g. file_shape) as there is no file.

Is that a convenient API?
What are you planning to do with the Waterfall object?

**Comment by texadactyl** [comment]
@Sofysicist
Ready for testing: blimpy 2.1.1.

**Comment by texadactyl** [comment]
@Sofysicist 
Reminder that blimpy 2.1.3 is ready for testing.
