### ISSUE TITLE
Typo in `waterfall.py`

### ISSUE THREAD

**Issue by wfarah** [UCBerkeleySETI/blimpy#266]
https://github.com/UCBerkeleySETI/blimpy/blob/master/blimpy/waterfall.py#L474

`kutosis` should be replaced with `kurtosis`. Not sure how that was working in the first place, and the plotting function not throwing an error?

**Comment by texadactyl** [comment]
I went back to blimpy 1.3.4 and the typo was there too.  It looks like the "Multiple diagnostic plots" option (```-p ank```) of ```watutil``` has never before been reported as an issue.

**Comment by texadactyl** [comment]
Fix verified
