### ISSUE TITLE
Rewrite GuppiRaw() reader to not raise EndOfFileError and use Context Management

### ISSUE THREAD

**Issue by christiangil** [UCBerkeleySETI/blimpy#29]
Using blimpy cloned from the Git repository from May 15th, 2018 (1.19?):

The GuppiRaw() method in blimpy is unable to import any raw file I have downloaded from the [open data search](http://breakthroughinitiatives.org/opendatasearch) website. Different .raw files produce different errors based on the size of the raw file it is trying to import (the larger files cannot be reshaped, while the smaller file reaches an end of file error). 

It may be the case that the chosen files are special and others do work with the method, but it is not clear to me that this is the case.

This can be seen in the following notebook:
https://github.com/christiangil/SETI-Final/blob/master/GuppiRaw_Testing.ipynb

**Comment by jeenriquez** [comment]
Greg, Danny, could you check on this? or can we close it?

**Comment by telegraphic** [comment]
This basically requires a rewrite of the GuppiRaw reader, so can't close it yet...

**Comment by telegraphic** [comment]
Changed title and added enhancement label. Relevant reading:
https://jeffknupp.com/blog/2016/03/07/python-with-context-managers/

**Comment by telegraphic** [comment]
Ok, I think it would be nice if we could run:

```python
with GuppiRaw(filename) as raw:
    for block in raw:
        print(block.header)
        print(block.data.shape)
```
I think this may need a `yield` function? Need to make sure that data are only loaded when needed, not at __init__
