### ISSUE TITLE
.fil files imported with Waterfall() unable to produce sliced spectrum plots

### ISSUE THREAD

**Issue by christiangil** [UCBerkeleySETI/blimpy#30]
Using blimpy cloned from the Git repository from May 15th, 2018 (1.19?):

The plot_spectrum() method used on .fil files imported with the Waterfall() method in blimpy is only able to produce spectrum plots that use the full, original frequency range of the imported filterbank file. This can be seen in cells 4 and 5 of a [recreated voyager tutorial notebook](https://github.com/christiangil/SETI-Final/blob/master/Voyager%20Tutorial%20p2%20Waterfall.ipynb) and cells 6 and 7 of a [recreated filterbank tutorial notebook](https://github.com/christiangil/SETI-Final/blob/master/Filterbank%20Tutorial%20p2%20Waterfall.ipynb) where the full spectrum is replotted, instead of the requested slice.

**Comment by jeenriquez** [comment]
I was able to reproduce this issue. I'll look into getting a fix soon.

**Comment by telegraphic** [comment]
Fixed in 1.2.0! (Please re-open or re-raise if I am being too hasty here). There are now automated checks that should catch all these, should they resurface.
