### ISSUE TITLE
.fil files imported with Filterbank() unable to produce sliced spectrum plots

### ISSUE THREAD

**Issue by christiangil** [UCBerkeleySETI/blimpy#31]
Using blimpy cloned from the Git repository from May 15th, 2018 (1.19?):

The plot_spectrum() method used on .fil files imported with the Filterbank() method in blimpy is only able to produce spectrum plots that use the full, original frequency range of the imported filterbank file. This can be seen in cells 4 and 5 of a [recreated voyager tutorial notebook](https://github.com/christiangil/SETI-Final/blob/master/Voyager%20Tutorial%20p2%20Filterbank.ipynb) and cells 6 and 8 of a [recreated filterbank tutorial notebook](https://github.com/christiangil/SETI-Final/blob/master/Filterbank%20Tutorial%20p2%20Filterbank.ipynb) where the spectrum is unable to be plotted due to a dimensional mismatch ("ValueError: x and y must have same first dimension, but have shapes (24L,) and (65536L,)").

Also of note is that once these commands end in an exception, the info() of the variable is modified (cell 7 of the [recreated filterbank tutorial notebook](https://github.com/christiangil/SETI-Final/blob/master/Filterbank%20Tutorial%20p2%20Filterbank.ipynb)) and it has to be reimported.

**Comment by jeenriquez** [comment]
I was able to reproduce this issue. I'm not going to fix it since we are moving more into just using Waterfall.
