### ISSUE TITLE
.fil files imported with Waterfall() unable to produce sliced waterfall plots

### ISSUE THREAD

**Issue by christiangil** [UCBerkeleySETI/blimpy#32]
Using blimpy cloned from the Git repository from May 15th, 2018 (1.19?):

The plot_waterfall() method used on .fil files imported with the Waterfall() method in blimpy is only able to produce waterfall plots that use the full, original frequency range of the imported filterbank file. This can be seen in cell 7 of a [recreated voyager tutorial notebook](https://github.com/christiangil/SETI-Final/blob/master/Voyager%20Tutorial%20p2%20Waterfall.ipynb) and cell 3 of a [recreated filterbank tutorial notebook](https://github.com/christiangil/SETI-Final/blob/master/Filterbank%20Tutorial%20p2%20Waterfall.ipynb) where the waterfall with the full spectrum is replotted, instead of the requested slices.

**Comment by telegraphic** [comment]
Fixed in 1.2.0!
