### ISSUE TITLE
Is time axis flipped in plot_all()?

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/blimpy#43]
In the attached, I reckon the burst in the waterfall should line up with the burst in the time vs power plot. So the time vs power on the RHS may need to be flipped? 

<img width="660" alt="screen shot 2018-07-27 at 1 25 52 pm" src="https://user-images.githubusercontent.com/713251/43300102-b3cf91e2-91a0-11e8-9517-e761950e7061.png">

**Comment by telegraphic** [comment]
Nice, I was using 1.3.3, so maybe this is already addressed

**Comment by jeenriquez** [comment]
can we close this Danny?

**Comment by telegraphic** [comment]
sure, let's close it
