### ISSUE TITLE
github releases missing?

### ISSUE THREAD

**Issue by gijzelaerr** [UCBerkeleySETI/blimpy#47]
Or, how can I find out which released version on pypi corresponds with which commit in the github repo?

**Comment by telegraphic** [comment]
I think this is adding a git --tag right that corresponds to the released versions on pypi?

**Comment by gijzelaerr** [comment]
2 things. You probably didn't push the tag. You can push tags with `$ git push --tags` or if you want to push all branches plus tags `$ git push --all --follow-tags`.

Second thing, a git tag doesn't automatically become a github release. I recommend pressing the `make new release` button on the GitHub interface to make a new release. 

https://help.github.com/articles/creating-releases/

You can also use a wrapper around git for github which enables you to make a github release from the CLI:

https://hub.github.com/

**Comment by david-macmahon** [comment]
I think only “annotated” tags can be pushed. You need to use `git tag -a ...` (or `-m`)

**Comment by gijzelaerr** [comment]
nah you can push any tag.

**Comment by david-macmahon** [comment]
Last time I checked, only annotated tags can be pushed.  Non-annotated tags are not git objects, they are just "pointers" in your local repo.

**Comment by david-macmahon** [comment]
Which repos have code that has been posted to pypi?  I agree that we should tag all versions of a repo that go to pypi.

**Comment by david-macmahon** [comment]
NVM, I see that this is a blimpy issue and not a bl_sw_meta issue

**Comment by telegraphic** [comment]
I am closing for now, it looks like we do have tags (https://github.com/UCBerkeleySETI/blimpy/tags). We should make sure tags match up to those on pypi going forward.
