### ISSUE TITLE
plot_waterfall with different cmap

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/blimpy#76]
If you try and do:

```python
fb.plot_waterfall(cmap='magma')
```

you will get an error as we hardcode `cmap='viridis'`, but pass through `**kwargs` from `plot_waterfall` to `plt.imshow`.

Solution is probably to use 
```python
cmap = kwargs.pop('cmap', 'viridis')
aspect = kwargs.pop('aspect', 'auto')
etc.
plt.imshow(..., cmap=cmap, aspect=aspect,...)
```

etc on all the hardcoded. This removes them from kwargs and fills in a default if it isn't specified..

**Comment by jeenriquez** [comment]
fixed Thanks FX196!!
